{% set version = "2.56" %}

package:
  name: perl-xml-parser
  version: {{ version }}

source:
  fn: XML-Parser-{{ version }}.tar.gz
  url: https://cpan.metacpan.org/authors/id/T/TO/TODDR/XML-Parser-{{ version }}.tar.gz
  sha256: a78bfcd3834fde7411acee2f5fcd74deeecfbaa8cee86f16c33c42dde2fd8fff

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make  # [unix]
    - sed   # [unix]
  host:
    - perl {{ perl }}
    - perl-file-sharedir-install 0.14
    - perl-file-sharedir 1.118
    - expat {{ expat }}
  run:
    - perl
    - perl-file-sharedir
    - expat

test:
  imports:
    - XML::Parser
    - XML::Parser::Expat
    - XML::Parser::Style::Debug
    - XML::Parser::Style::Objects
    - XML::Parser::Style::Stream
    - XML::Parser::Style::Subs
    - XML::Parser::Style::Tree

about:
  home: https://metacpan.org/pod/XML::Parser
  # According to http://dev.perl.org/licenses/ Perl5 is licensed either under
  # GPL v1 or later or the Artistic License
  license: Artistic-1.0-Perl
  license_family: Other
  license_file: LICENSE
  summary: A perl module for parsing XML documents
  description: |
    This module provides ways to parse XML documents. It is built on top
    of XML::Parser::Expat, which is a lower level interface to James
    Clark's expat library.
  doc_url: https://metacpan.org/pod/XML::Parser
  dev_url: https://metacpan.org/pod/XML::Parser

extra:
  recipe-maintainers:
    - kynan
    - scopatz
    - katietz
