travis:
  secure:
    BINSTAR_TOKEN: pD0zN5KxPiADUzntvPs8bscYAlvE9Z7t3b+rxjRLNhfqFRY/NOdWXz76G0CjlnmCxKXirRuzbkh4XGWvlHiWavNN4SAT9gLA03J26tGlAOVmlHjRgwbhyyCOooE74uLc1pun00bpUzFnp3VoGRWfl2RJqnlq0TupFrBkuCqVuXN4LMW1+nbE3M8nU8+87U5RmgLAVKK3fyfe6BZ5cgeFze6T8fXcmsVFgANfEAvJTJJ3iRCkaOPcrYEQinB9Vo+RfOfZoalo6E5ATXmLkBAkRdeV1ODn4qG3+ZgY6oxHuZGzecEu/AuHc2Tb91SxBhG4Cwh2nWm1i3R6lVOaXnTSlF6a/9A7VRUeY+LuTsmXNugvTxUmhvw6k4CJ/oXw2uDgvxk08H4r36z7xocyVpw3nyI6wuPbO0F3P/l+n6IdXluk+xEekFqL3eV3oY4pbi/3UO1J5Lg54JbMEc4NSgxEDMV5fiKQ2n5xQAsJMgIpQlAMREOZjUR1uFpB42YwZ5AGJ8C5fRG31PU2J0YaGnEChf+l+dhLzDibLYgeQJ93djG2xGpxB4i1WM3ImrWTIAUIbAR4Led7Gmg9BZxnOUe2FIqwSnvLWVies38bK6Dib5dcw2wuKZ+nlICqkDFq+t1cg+3USENrHL13GjQnRSGkDWm5ktU6gta1U6mIVecFLlE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
