appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: kcnKcAlNpBIO/HsNUIez4aTLXWe2z2FYWzYsbppMjPWhuEBeg61ZBFQpXC7jYTvYZTeaFRJXcufJ57go2C2z2PdtIDInkmPiyyasGXx8uaNjbYtWcb1Q3nVGUwqORiPn2R7focdaQbLHPXiDz+/lAKB6gyop6ZP0gPnUctWWHtg3Y9bM4Um6Ksd3PWIIwbkPuhVa9Cf5Y/mb7kcb2Mq9jEh9jGaEPPcpzBtuiel6PCwlXtxDgPi9G2rhAPAU7TqceL1oefvjk1q9IdmSIbFUimp/i9l0eiz1ZolNQgWp+w1NwoD3udRoHu3hQkGriTHKBECbO08uBEb+ZfdALT1gMqrBq4K6cyxM+ZUvg9Tayxhn2Rg0ja0ITb+TIyBWPbhmpnjRQdfUt1XlXCeLUp28nS0ioCT3NFhVN4G3NW07pSWUmtDmeHCM/m9ZdSF+Rx2OHw3Qdt9/xsYxN3eQ3Pu8R0DbeFBpcFuOqpDLZTmltu516g7clFHzqqTgXXW2c5h+/KMEIzPLBiazSagibO5C2I1wmW5zkGeDzMB8wTgG5QZc3/obowx9nsGnE9RQlC88c0KxUyGZWD64WhvpurCU/sNg6X2q4xanYMyPK8rf4BTNI9I1x8d7C3RvTult/bdR1UnCP5znznqp1T6j1uwrW/ZDLynZcD8oVlYWLly4bZU=}
conda_forge_output_validation: true
